pipeline {

    agent any
    stages{
            stage('Bulid Application'){
                steps {

                    sh 'mvn clean package'
                }
                post {
                    success {
                        echo "Now Archiving the Artifacts..."
                        archiveArtifacts artifacts: '**/*.war'
                    }

                }
            }
    }
}
