pipeline {

    agent any
    stages{
            stage('Bulid Application'){
                steps{

                    sh 'mvn clean package'
                }
                post{
                    success{
                        echo "Now Arching the Artifacts"
                        archiveArtifacts artifacts: '**/*.war'
                    }

                }
            }
    }
}
