pipeline {

    agent any
    stages{
            stage('Bulid Application'){
                steps{

                    sh 'mvn -f java-tomcat-sample/pom.xml clean package'
                }
                post{
                    success{
                        echo "Now Arching the Artifacts"
                        archiveArtifacts artifacts '**/*.war'
                    }

                }

                stage('Deploy the stating enviromnet')
                steps{
                build job: 'eploy-Application-Staging-Env'

            }

                  
            }


    }
}
